[theme]
base = "dark"
primaryColor = "#800020"
backgroundColor = "#000000"          # Dark background
secondaryBackgroundColor = "#262730"  # Secondary dark
textColor = "#FAFAFA"                # Light text



[server]
headless = true
enableCORS = false
port = 8501
