[theme]
# Light mode configuration for MIND Dashboard
base = "light"
primaryColor = "#800020"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"


base = "dark"
primaryColor = "#800020"
backgroundColor = "#000000"          # Dark background
secondaryBackgroundColor = "#262730"  # Secondary dark
textColor = "#FAFAFA"                # Light text



[server]
headless = true
enableCORS = false
port = 8501
